# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://fabriciomasiero.github.io'
baseurl: ''
title: 'Fabrício Masiero iOS Engineer'
description: 'Swift Daily'
permalink: pretty
logo: "https://secure.gravatar.com/avatar/e8aad27c12f50d24f6d9bc759d08710e"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: About Me
  url: /
# - title: About Me
  # url: /about/
- title: Posts
  url: /blog/

# Footer nav
navigation_footer:
# - title: Back to top
  # url: "#top"

# Posts
collections:
  posts:
    title: Posts
    output: true
    description: ""
    feature_text:
    feature_image: "https://images.unsplash.com/photo-1514428631868-a400b561ff44?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80"
